### ISSUE TITLE
Fine-tuning pretrained models

### ISSUE THREAD

**Issue by jakob-ed** [argosopentech/argos-translate#143]
First, thank you for this project! I would like to improve translation performance for my specific use case using transfer learning. How would I go about fine-tuning a pretrained model from the [index](https://www.argosopentech.com/argospm/index/) to adapt it better to a specific domain? 

I did some digging myself and I guess I would need to "unconvert" the model.bin file (I'm looking at the German-to-English model) generated with ctranslate2 to get to the actual weights. However, I can't see how I could accomplish this.

**Comment by PJ-Finlay** [comment]
Thanks!

I recommend training a new model from scratch instead of fine tuning, if you want to fine tune though try asking on the [OpenNMT Forum](https://forum.opennmt.net/). Training a usable model only takes a day or two on a good GPU, and the argos-train library in the [training scripts](https://github.com/argosopentech/onmt-models) helps with composing datasets. I would get some/all of the [Opus](https://opus.nlpl.eu/) data, combine it with your custom data, and then create a new package.
