### ISSUE TITLE
C++ usage for argosmodels

### ISSUE THREAD

**Issue by johnpaulbin** [argosopentech/argos-translate#222]
Hi there, I've been looking into translating argosmodels for a while now, and I want to know how to translate your pre-trained .argosmodels on C++.

Is there a sample script that describes the steps?

**Comment by PJ-Finlay** [comment]
You would need to use CTranslate2 to do inference on the models, and SentencePiece for tokenization (both in C++).

You would need to figure something else out for sentence boundary detection because Argos Translate uses Stanza which is only available for Python. One option is to do something like [this](https://github.com/argosopentech/argos-translate/blob/fc018483fda07423c8a200662da0bf39c4efea4b/argostranslate/sbd.py#L68).
