### ISSUE TITLE
Security questions

### ISSUE THREAD

**Issue by valasek** [argosopentech/argos-translate#251]
Hi PJ FInlay,

first of all thank you for this amazing piece of SW. We plan to use is via page https://libretranslate.com/ but would like to translate sensitive medical and personal information.

Here is what we would like to know:
- does the page https://libretranslate.com/ persist translated data? If yes, for how long, where and how are data encrypted at test?
- how are the data encrypted at transit - between the page and translation model?

Thank you and feel free to link the relevant source files I fell we might be able to figure it out - if relevant code is available.

**Comment by bruceleerabbit** [comment]
I can’t answer your questions, but instead of using the website I suggest installing the app and running this command:
```
firejail --net=none argos-translate --from-lang fr --to-lang en 'Bonjour'
```
If you install argos-translate then you don’t need trust.  All the translation is done locally on your own host.  For many that is secure enough, but adding `firejail --net=none` further guarantees that nothing is transmitted over the Internet.

**Comment by PJ-Finlay** [comment]
If you're using [libretranslate.com](https://libretranslate.com) its site operators will be able to access your data (it's run by @pierotofy ). You can also host LibreTranslate yourself, which doesn't connect to external services, or run Argos Translate on a Linux or Mac desktop if you're concerned about privacy.
