### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by PJ-Finlay** [argosopentech/argos-translate#30]
The plan is to use GitLab for CI. The first step is to update [scripts/update_to_pypi.sh](https://github.com/argosopentech/argos-translate/blob/3bad3426bb0d480a9cc6aa3c329a41bf732cfda5/scripts/update_to_pypi.sh) to automate uploading a new version to PyPI.

**Comment by vemonet** [comment]
Copy pasting my comments about GitLab CI vs GitHub Actions in another issue

GitHub Actions vs GitLab CI is basically the same if you just aim to do basic `pytest` run

imo the best is to just use the one where your host your code, apart if you need specific features from the other CI

From my experience GitLab CI is more mature and give more possibilities when it comes to deploy self-hosted runners anywhere (e.g. kubernetes). GitHub Actions is working on it but not completely there (they recently announced an official partnerships with Red Hat OpenShift for that, so we can expect something coming soon)

But also from my experience GitHub Actions is much more user-friendly, as it is built for developers, not sysadmin/DevOps (GitLab is more technical and will require regular developers more effort to learn). Since they started later they had more experience and use-cases feedbacks to make the framework more user friendly. Also as bonus, Secrets and workflow triggers are easier to setup in GitHub Actions

I even have been using GitHub Actions for long data processing workflows, and it's really stable and easy to maintain

For short, in my opinion:
* You are a developer who's building an open source library hosted on GitHub, and you want to quickly get your things done without the need to know Linux arcanes (thanks the actions marketplace)? Use GitHub Actions
* You are a developer who is building libraries on GitLab (gitlab.com or self-hosted), or you want to deploy complex workflow to various self-hosted platforms? Go with GitLab CI

In our case it does not really matter, the same pytest can be easily run on GitLab CI or GitHub Actions, you just need to put the bash commands in a different YAML format :)

**Comment by vemonet** [comment]
Here is an example of a simple GitHub Actions workflow that will test and publish to pypi your package (need to uncomment the tests)

https://github.com/uav4geo/LibreTranslate/blob/90d743796b04554104fb24738a83664fb6720ef6/.github/workflows/publish-package.yml

You just need to add the secret in your GitHub repository settings

**Comment by PJ-Finlay** [comment]
If you want to implement it with GitHub I'll accept a pull request since future switching costs would be low to move to GitLab. I can add secretes. I haven't been pushing often enough to PyPI for it to be a high priority.

**Comment by vemonet** [comment]
If you already have working workflow with GitLab CI that does not really make sense to duplicate those, apart if GitHub actions brings new features for you

Also, I was thinking triggering GitLab CI from a repo hosted on GitHub would add a more of complexity to setup the workflow. I am actually interested in doing it so I will probably take a look on it

**Comment by PJ-Finlay** [comment]
I don't have any immediate plans for Gitlab and it may make sense long term to do this project on GitHub even if I'm using Gitlab for other things. I'm not worried about getting locked into either one because it's mostly just shell scripts. The main thing we would want is to upload to PyPI, the snapcraft upload is probably too flaky for CI for now. Testing too but the tests need to be written first.
