### ISSUE TITLE
update your dependencies

### ISSUE THREAD

**Issue by tpcgold** [argosopentech/argos-translate#362]
the dependencies are way too strict as only stanza 1.1.1 is supported. 
update your dependencies and allow newer versions (as they still work perfectly)

also the strict requirements lead to issues using other libraries like spacy in the same project as argostranslate

**Comment by PJ-Finlay** [comment]
Have you tested that Argos Translate works with new versions of Stanza? I haven't increased the Stanza version so that all Argos Translate models are using the same version which I thought would reduce version conflicts. If a changing to `>=1.1.1` would work better I can accept a pull request to do this.

**Comment by tpcgold** [comment]
changing would work. 
i have only tested argos translate on the models i need so cant guarantee that all models support a newer stanza version.

you got a pull request here:
https://github.com/argosopentech/argos-translate/pull/377
